### PR TITLE
bug: Fix <hr> insertion before styled non-empty <p>

### LINKED ISSUE #27: Inserting hr before non empty paragraph
In 7b457769eaed0c304d27387dd1980dbbeda0ad87, `prevSibling` is assigned the `previousSibling` of `selection.anchorNode`. The problem is that when the user presses enter and the caret is at the beginning of a non-empty paragraph, `selection.anchorNode` is the text node inside the paragraph, not the paragprah itself.

Because of this, inserting a hr before an existing paragraph is broken right now, as `prevSibling` isn't the expected node.

In that situation in medium, the first enter keypress inserts an hr, the second a paragraph, etc. This makes it possible to stack empty paragraph and hrs, so that might be a bug on their end but not a very important one.

Using `selection.anchorNode.parentNode` is probably not robust enough either, because if the paragraph starts with an `i` tag, we'll get the text node _inside_ the `i`. This is why I initially used `getParentWithTag` but it feels a bit hacky.

### PR DESCRIPTION
**Pull request by mduvall**
Fixes https://github.com/mduvall/grande.js/issues/27.

### CODE REVIEW

File: js/grande.js [hunk 1]
```diff
@@ -165,21 +171,43 @@
...
+        parentParagraph.parentNode.replaceChild(hr, prevSibling);
+        return;
+      }
 
-      if (prevSibling.nodeName === "P" && !prevSibling.textContent.length) {
-        hr = document.createElement("hr");
-        hr.contentEditable = false;
-        sel.anchorNode.parentNode.replaceChild(hr, prevSibling);
+      // Insert before non-empty <p>
+      prevPrevSibling = parentParagraph.previousSibling.previousSibling;
```
Comment (mduvall) [inline js/grande.js]: Iffy about this, it basically checks two siblings up to make sure it's a `<p>` and replaces the `previousSibling` with a `<hr>` since they are both empty at this point. It mimics the behavior Medium has which to me seems not so intuitive.

File: js/grande.js [hunk 2]
```diff
@@ -165,21 +171,43 @@
...
+        hr;
+
+    prevSibling = parentParagraph.previousSibling;
+
+    if (prevSibling.nodeName === "P" && !prevSibling.textContent.length) {
+      hr = document.createElement("hr");
+      hr.contentEditable = false;
+
+      if (!parentParagraph.textContent.length) {
+        parentParagraph.parentNode.replaceChild(hr, prevSibling);
```
Comment (mduvall) [inline js/grande.js]: Here basically if the current paragraph has no content and we are adding another line, this is the typical case to insert the `<hr>`.

**Comment by mduvall** [comment]
@y-lohse This looks pretty good, going to merge this in now.
